const currencies = [
  {
    country: "Afghanistan",
    flag: "🇦🇫",
    name: "Afghan Afghani",
    code: "AFN",
    symbol: "؋",
  },
  {
    country: "Albania",
    flag: "🇦🇱",
    name: "Albanian Lek",
    code: "ALL",
    symbol: "L",
  },
  {
    country: "Algeria",
    flag: "🇩🇿",
    name: "Algerian Dinar",
    code: "DZD",
    symbol: "دج",
  },
  {
    country: "Andorra",
    flag: "🇦🇩",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "Angola",
    flag: "🇦🇴",
    name: "Angolan Kwanza",
    code: "AOA",
    symbol: "Kz",
  },
  {
    country: "Antigua and Barbuda",
    flag: "🇦🇬",
    name: "East Caribbean Dollar",
    code: "XCD",
    symbol: "$",
  },
  {
    country: "Argentina",
    flag: "🇦🇷",
    name: "Argentine Peso",
    code: "ARS",
    symbol: "$",
  },
  {
    country: "Armenia",
    flag: "🇦🇲",
    name: "Armenian Dram",
    code: "AMD",
    symbol: "֏",
  },
  {
    country: "Australia",
    flag: "🇦🇺",
    name: "Australian Dollar",
    code: "AUD",
    symbol: "$",
  },
  {
    country: "Austria",
    flag: "🇦🇹",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "Azerbaijan",
    flag: "🇦🇿",
    name: "Azerbaijani Manat",
    code: "AZN",
    symbol: "₼",
  },
  {
    country: "Bahamas",
    flag: "🇧🇸",
    name: "Bahamian Dollar",
    code: "BSD",
    symbol: "$",
  },
  {
    country: "Bahrain",
    flag: "🇧🇭",
    name: "Bahraini Dinar",
    code: "BHD",
    symbol: ".د.ب",
  },
  {
    country: "Bangladesh",
    flag: "🇧🇩",
    name: "Bangladeshi Taka",
    code: "BDT",
    symbol: "৳",
  },
  {
    country: "Barbados",
    flag: "🇧🇧",
    name: "Barbadian Dollar",
    code: "BBD",
    symbol: "$",
  },
  {
    country: "Belarus",
    flag: "🇧🇾",
    name: "Belarusian Ruble",
    code: "BYN",
    symbol: "Br",
  },
  {
    country: "Belgium",
    flag: "🇧🇪",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "Belize",
    flag: "🇧🇿",
    name: "Belize Dollar",
    code: "BZD",
    symbol: "BZ$",
  },
  {
    country: "Benin",
    flag: "🇧🇯",
    name: "West African CFA Franc",
    code: "XOF",
    symbol: "CFA",
  },
  {
    country: "Bhutan",
    flag: "🇧🇹",
    name: "Bhutanese Ngultrum",
    code: "BTN",
    symbol: "Nu.",
  },
  {
    country: "Bolivia",
    flag: "🇧🇴",
    name: "Bolivian Boliviano",
    code: "BOB",
    symbol: "Bs.",
  },
  {
    country: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    name: "Convertible Mark",
    code: "BAM",
    symbol: "KM",
  },
  {
    country: "Botswana",
    flag: "🇧🇼",
    name: "Botswana Pula",
    code: "BWP",
    symbol: "P",
  },
  {
    country: "Brazil",
    flag: "🇧🇷",
    name: "Brazilian Real",
    code: "BRL",
    symbol: "R$",
  },
  {
    country: "Brunei",
    flag: "🇧🇳",
    name: "Brunei Dollar",
    code: "BND",
    symbol: "$",
  },
  {
    country: "Bulgaria",
    flag: "🇧🇬",
    name: "Bulgarian Lev",
    code: "BGN",
    symbol: "лв",
  },
  {
    country: "Burkina Faso",
    flag: "🇧🇫",
    name: "West African CFA Franc",
    code: "XOF",
    symbol: "CFA",
  },
  {
    country: "Burundi",
    flag: "🇧🇮",
    name: "Burundian Franc",
    code: "BIF",
    symbol: "FBu",
  },
  {
    country: "Cabo Verde",
    flag: "🇨🇻",
    name: "Cape Verdean Escudo",
    code: "CVE",
    symbol: "$",
  },
  {
    country: "Cambodia",
    flag: "🇰🇭",
    name: "Cambodian Riel",
    code: "KHR",
    symbol: "៛",
  },
  {
    country: "Cameroon",
    flag: "🇨🇲",
    name: "Central African CFA Franc",
    code: "XAF",
    symbol: "FCFA",
  },
  {
    country: "Canada",
    flag: "🇨🇦",
    name: "Canadian Dollar",
    code: "CAD",
    symbol: "$",
  },
  {
    country: "Central African Republic",
    flag: "🇨🇫",
    name: "Central African CFA Franc",
    code: "XAF",
    symbol: "FCFA",
  },
  {
    country: "Chad",
    flag: "🇹🇩",
    name: "Central African CFA Franc",
    code: "XAF",
    symbol: "FCFA",
  },
  {
    country: "Chile",
    flag: "🇨🇱",
    name: "Chilean Peso",
    code: "CLP",
    symbol: "$",
  },
  {
    country: "China",
    flag: "🇨🇳",
    name: "Chinese Yuan",
    code: "CNY",
    symbol: "¥",
  },
  {
    country: "Colombia",
    flag: "🇨🇴",
    name: "Colombian Peso",
    code: "COP",
    symbol: "$",
  },
  {
    country: "Comoros",
    flag: "🇰🇲",
    name: "Comorian Franc",
    code: "KMF",
    symbol: "CF",
  },
  {
    country: "Congo",
    flag: "🇨🇬",
    name: "Central African CFA Franc",
    code: "XAF",
    symbol: "FCFA",
  },
  {
    country: "Costa Rica",
    flag: "🇨🇷",
    name: "Costa Rican Colón",
    code: "CRC",
    symbol: "₡",
  },
  {
    country: "Côte d'Ivoire",
    flag: "🇨🇮",
    name: "West African CFA Franc",
    code: "XOF",
    symbol: "CFA",
  },
  {
    country: "Croatia",
    flag: "🇭🇷",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "Cuba",
    flag: "🇨🇺",
    name: "Cuban Peso",
    code: "CUP",
    symbol: "$",
  },
  {
    country: "Cyprus",
    flag: "🇨🇾",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "Czech Republic",
    flag: "🇨🇿",
    name: "Czech Koruna",
    code: "CZK",
    symbol: "Kč",
  },
  {
    country: "Democratic Republic of the Congo",
    flag: "🇨🇩",
    name: "Congolese Franc",
    code: "CDF",
    symbol: "FC",
  },
  {
    country: "Denmark",
    flag: "🇩🇰",
    name: "Danish Krone",
    code: "DKK",
    symbol: "kr",
  },
  {
    country: "Djibouti",
    flag: "🇩🇯",
    name: "Djiboutian Franc",
    code: "DJF",
    symbol: "Fdj",
  },
  {
    country: "Dominica",
    flag: "🇩🇲",
    name: "East Caribbean Dollar",
    code: "XCD",
    symbol: "$",
  },
  {
    country: "Dominican Republic",
    flag: "🇩🇴",
    name: "Dominican Peso",
    code: "DOP",
    symbol: "RD$",
  },
  {
    country: "Ecuador",
    flag: "🇪🇨",
    name: "United States Dollar",
    code: "USD",
    symbol: "$",
  },
  {
    country: "Egypt",
    flag: "🇪🇬",
    name: "Egyptian Pound",
    code: "EGP",
    symbol: "£",
  },
  {
    country: "El Salvador",
    flag: "🇸🇻",
    name: "United States Dollar",
    code: "USD",
    symbol: "$",
  },
  {
    country: "Equatorial Guinea",
    flag: "🇬🇶",
    name: "Central African CFA Franc",
    code: "XAF",
    symbol: "FCFA",
  },
  {
    country: "Eritrea",
    flag: "🇪🇷",
    name: "Eritrean Nakfa",
    code: "ERN",
    symbol: "Nfk",
  },
  {
    country: "Estonia",
    flag: "🇪🇪",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "Eswatini",
    flag: "🇸🇿",
    name: "Swazi Lilangeni",
    code: "SZL",
    symbol: "E",
  },
  {
    country: "Ethiopia",
    flag: "🇪🇹",
    name: "Ethiopian Birr",
    code: "ETB",
    symbol: "Br",
  },
  {
    country: "Fiji",
    flag: "🇫🇯",
    name: "Fijian Dollar",
    code: "FJD",
    symbol: "$",
  },
  {
    country: "Finland",
    flag: "🇫🇮",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "France",
    flag: "🇫🇷",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "Gabon",
    flag: "🇬🇦",
    name: "Central African CFA Franc",
    code: "XAF",
    symbol: "FCFA",
  },
  {
    country: "Gambia",
    flag: "🇬🇲",
    name: "Gambian Dalasi",
    code: "GMD",
    symbol: "D",
  },
  {
    country: "Georgia",
    flag: "🇬🇪",
    name: "Georgian Lari",
    code: "GEL",
    symbol: "₾",
  },
  {
    country: "Germany",
    flag: "🇩🇪",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "Ghana",
    flag: "🇬🇭",
    name: "Ghanaian Cedi",
    code: "GHS",
    symbol: "₵",
  },
  {
    country: "Greece",
    flag: "🇬🇷",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "Grenada",
    flag: "🇬🇩",
    name: "East Caribbean Dollar",
    code: "XCD",
    symbol: "$",
  },
  {
    country: "Guatemala",
    flag: "🇬🇹",
    name: "Guatemalan Quetzal",
    code: "GTQ",
    symbol: "Q",
  },
  {
    country: "Guinea",
    flag: "🇬🇳",
    name: "Guinean Franc",
    code: "GNF",
    symbol: "FG",
  },
  {
    country: "Guinea-Bissau",
    flag: "🇬🇼",
    name: "West African CFA Franc",
    code: "XOF",
    symbol: "CFA",
  },
  {
    country: "Guyana",
    flag: "🇬🇾",
    name: "Guyanese Dollar",
    code: "GYD",
    symbol: "$",
  },
  {
    country: "Namibia",
    flag: "🇳🇦",
    name: "Namibian Dollar",
    code: "NAD",
    symbol: "$",
  },
  {
    country: "Nepal",
    flag: "🇳🇵",
    name: "Nepalese Rupee",
    code: "NPR",
    symbol: "₨",
  },
  {
    country: "Netherlands",
    flag: "🇳🇱",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "New Zealand",
    flag: "🇳🇿",
    name: "New Zealand Dollar",
    code: "NZD",
    symbol: "$",
  },
  {
    country: "Nicaragua",
    flag: "🇳🇮",
    name: "Nicaraguan Córdoba",
    code: "NIO",
    symbol: "C$",
  },
  {
    country: "Niger",
    flag: "🇳🇪",
    name: "West African CFA Franc",
    code: "XOF",
    symbol: "CFA",
  },
  {
    country: "Nigeria",
    flag: "🇳🇬",
    name: "Nigerian Naira",
    code: "NGN",
    symbol: "₦",
  },
  {
    country: "North Macedonia",
    flag: "🇲🇰",
    name: "Macedonian Denar",
    code: "MKD",
    symbol: "ден",
  },
  {
    country: "Norway",
    flag: "🇳🇴",
    name: "Norwegian Krone",
    code: "NOK",
    symbol: "kr",
  },
  {
    country: "Laos",
    flag: "🇱🇦",
    name: "Lao Kip",
    code: "LAK",
    symbol: "₭",
  },
  {
    country: "Latvia",
    flag: "🇱🇻",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "Lebanon",
    flag: "🇱🇧",
    name: "Lebanese Pound",
    code: "LBP",
    symbol: "£",
  },
  {
    country: "Lesotho",
    flag: "🇱🇸",
    name: "Lesotho Loti",
    code: "LSL",
    symbol: "L",
  },
  {
    country: "Liberia",
    flag: "🇱🇷",
    name: "Liberian Dollar",
    code: "LRD",
    symbol: "$",
  },
  {
    country: "Libya",
    flag: "🇱🇾",
    name: "Libyan Dinar",
    code: "LYD",
    symbol: "ل.د",
  },
  {
    country: "Liechtenstein",
    flag: "🇱🇮",
    name: "Swiss Franc",
    code: "CHF",
    symbol: "CHF",
  },
  {
    country: "Lithuania",
    flag: "🇱🇹",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "Luxembourg",
    flag: "🇱🇺",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  
  {
    country: "Finland",
    flag: "🇫🇮",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
  {
    country: "France",
    flag: "🇫🇷",
    name: "Euro",
    code: "EUR",
    symbol: "€",
  },
];
export default currencies;
